### ISSUE TITLE
CartLine.discountAllocations cannot pass the model conversion correctly.

### ISSUE THREAD

**Issue by WangXiaoRi** [imsujan276/shopify_flutter#94] opened 2024-09-27 09:17 UTC
The interface returns a result, but there is no value obtained in cartLine model.

**Comment by imsujan276** [comment] 2024-09-27 09:33
Can you add more context to it?

**Comment by WangXiaoRi** [comment] 2024-09-27 09:40
![461727429852_ pic](https://github.com/user-attachments/assets/cd01ad5f-75d9-4f63-b378-38e3db9281c4)
![471727429874_ pic](https://github.com/user-attachments/assets/d7c8a2aa-f47e-49a9-98a1-b260cb671d9f)
![481727429912_ pic](https://github.com/user-attachments/assets/3599449f-1732-4408-9934-22361d2c3288)
You can try to apply the coupon and the discount is empty here.

**Comment by imsujan276** [comment] 2024-09-27 10:41
why is the `discountAllocations` started with `_` as `_discountAllocations`. I think that is the cause of it

**Comment by WangXiaoRi** [comment] 2024-09-29 02:22
thanks.

**Comment by FrancoTerranovaJob** [comment] 2024-10-03 19:13
Same problem here, I think this is critical. Please, need fix soon @imsujan276.

**Comment by imsujan276** [comment] 2024-10-04 08:15
This issue has been resolved in v2.2.5

**Closed by imsujan276** 2024-10-04 08:15 UTC

**Comment by WangXiaoRi** [comment] 2024-10-08 01:23
thanks
